# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Charts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Charts

  target 'ChartsTests' do
    # Pods for testing
  end

end
